/**
 * CONTENT API — signatures owned by the architect, implementation owned by the content agent.
 *
 * Pages, routing and prerender import ONLY from here ("@/content"). The exported function
 * signatures below are the contract and must not change without the architect's sign-off.
 *
 * Where the data comes from
 * - "virtual:content" is generated by the Vite plugin in scripts/lib/content-plugin.ts: it
 *   reads every file under /content, validates it with the zod schema (./schema.ts) and
 *   removes unpublished items before anything reaches a bundle. Invalid content fails the
 *   dev server / the build with a list of problems. Incomplete but harmless content is
 *   tidied instead (a missing optional value gets its default, blank list rows are dropped),
 *   so every object returned here has every field of ./types.ts.
 * - The functions themselves live in ./selectors.ts as pure functions over that data.
 *
 * Rules for the implementation
 * - Works in the browser bundle and in the SSR/prerender bundle (no fs, no window, no zod).
 * - Unpublished items are filtered out here as well and never reach callers.
 * - All functions are synchronous and return new arrays (callers may sort/slice them).
 */
import content from 'virtual:content';
import { createContentApi } from './selectors';
import type {
  Certificate,
  Education,
  Project,
  ResolvedExperience,
  SiteSettings,
  SkillGroup,
  SocialLink,
  Tab,
  TrackId,
  TrackProfile,
} from './types';

export type * from './types';

const api = createContentApi(content);

// ---------------------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------------------

/** content/site.json */
export function getSite(): SiteSettings {
  return api.getSite();
}

/** Both track profiles, game first. */
export function getTracks(): TrackProfile[] {
  return api.getTracks();
}

export function getTrack(id: TrackId): TrackProfile {
  return api.getTrack(id);
}

/** Track whose route segment matches ("gamedev" | "softdev"), or undefined. */
export function getTrackByRoute(route: string): TrackProfile | undefined {
  return api.getTrackByRoute(route);
}

/** Categories in order, followed by the "all" tab. Same list on every page. */
export function getTabs(): Tab[] {
  return api.getTabs();
}

/** tabId if it is a valid tab id, otherwise the track's default tab. */
export function resolveTab(track: TrackId, tabId: string | undefined): string {
  return api.resolveTab(track, tabId);
}

/**
 * Published projects for one page and one tab.
 * tab = category id or "all". Sort: featured first, then (on the "all" tab) projects whose
 * audience matches the track or is "both", then the track's order field, then title.
 */
export function getProjects(track: TrackId, tab: string): Project[] {
  return api.getProjects(track, tab);
}

/** Card hover text for a project: its own hoverText, else the category default. */
export function getHoverText(project: Project): string {
  return api.getHoverText(project);
}

/**
 * Published experience for one page. Entries whose audience matches the track (or "both")
 * come first, each group sorted by the track's order field. resolvedBullets holds the
 * track-specific bullet set when it is non-empty, else the default bullets.
 */
export function getExperience(track: TrackId): ResolvedExperience[] {
  return api.getExperience(track);
}

/** Published skill groups sorted by the track's order field. */
export function getSkillGroups(track: TrackId): SkillGroup[] {
  return api.getSkillGroups(track);
}

/**
 * Published links visible on this page for one placement. The two placements have their own
 * order: "hero" sorts by `order`, "footer" by `orderFooter` (ties: `order`, then slug).
 * Links whose url is empty are left out, so a renderer never gets a button with nowhere to go.
 */
export function getLinks(track: TrackId, placement: 'hero' | 'footer'): SocialLink[] {
  return api.getLinks(track, placement);
}

/** The resume button for one page while `tabId` is the open tab. Falls back to the track's own resume. */
export function getResume(track: TrackId, tabId: string): { url: string; label: string } {
  return api.getResume(track, tabId);
}

/** Published education entries sorted by order. */
export function getEducation(): Education[] {
  return api.getEducation();
}

/** Published certificates sorted by the track's order field. */
export function getCertificates(track: TrackId): Certificate[] {
  return api.getCertificates(track);
}

/**
 * Every public route to prerender, without the base path and without a trailing slash,
 * for example: "/", "/gamedev", "/gamedev/unity", "/gamedev/all", "/softdev", "/softdev/webapps".
 */
export function getAllRoutes(): string[] {
  return api.getAllRoutes();
}
