/**
 * "virtual:content" is generated by scripts/lib/content-plugin.ts (registered in
 * vite.config.ts): the files under /content, validated, with unpublished items removed.
 * Import it only from src/content/index.ts; everything else goes through "@/content".
 */
declare module 'virtual:content' {
  const content: import('./bundle').ContentBundle;
  export default content;
}
